COMMAND_SIZE = 9
INT_SIZE = 8
UP       = "w        "
OBJ_OP   = "obj_obj   "
LEFT     = "a        "
DOWN     = "s        "
RIGHT    = "d        "
INTERACT = "e        "
END_OP   = "stop     "
UDP_PORT = "udp      "
START    = "game     "
PORT = 35324
SERVER_ADDRESS = "127.0.0.1"
