COMMAND_SIZE = 9
INT_SIZE = 8
TILESIZE = 64
SCREEN_WIDTH = 13
SCREEN_HEIGHT = 8
WIN_SCORE = 10
INTERACT_BUFFER = 30
UP       = "w        "
OBJ_OP   = "obj_obj   "
LEFT     = "a        "
DOWN     = "s        "
RIGHT    = "d        "
INTERACT = "e        "
END_OP   = "stop     "
UDP_PORT = "udp      "
START    = "game     "
PORT = 35332
SERVER_ADDRESS = "127.0.0.1"
